gles-user-module: Provide "virtual/libgl" to make glmark2 build happy
Otherwise adding glmark2 and kmscube apps as the installation candidates
in meta-xt-common leads to the build issue (the path below is slightly adjusted):

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'virtual/libgl' (but .../glmark2_git.bb DEPENDS on or otherwise requires it)
mesa PROVIDES virtual/libgl but was skipped: PREFERRED_PROVIDER_virtual/libgbm set to libgbm, not mesa
NOTE: Runtime target 'glmark2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['glmark2', 'virtual/libgl']
ERROR: Required build target 'core-image-weston' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-weston', 'glmark2', 'virtual/libgl']

Please note, I am not quite sure whether it is a 100% correct change,
but the build is passed and these apps work on the target.

Tested on salvator-x-h3-4x2g machine only.

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>