python-clang: Fix misc QA issues which have appeared since Kirkstone
WARNING: QA Issue: python-clang: native/nativesdk class is not inherited last,
this can result in unexpected behaviour. Classes inherited after native/nativesdk:
pypi.bbclass [native-last]

ERROR: ../python-clang_5.0.post2.bb: QA Issue: ../python-clang_5.0.post2.bb:
Variable RDEPENDS is set as not being package specific, please fix this. [pkgvarcheck]

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>